name: e2e Test and Publish Result

# mainブランチに対してpushされたタイミングで実行
on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  RunPytest:
    runs-on: ubuntu-latest
    env:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      # リポジトリをチェックアウト
      - uses: actions/checkout@v3.4.0

      # Pythonの環境をセットアップ
      - name: Setup Python 3.10
        uses: actions/setup-python@v4.5.0
        with:
          python-version: '3.10'

      # 必要なパッケージをインストール
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install playwright
          python -m playwright install --with-deps
          pip install pytest
          pip install pytest-playwright

      # テスト実行. テスト失敗時も継続
      - name: PyTest
        run: |
          python -m pytest tests/test_practice3.py --junit-xml results/pytest.xml
        continue-on-error: true

      # テスト結果の表示
      - name: Upload Test Results
        if: ${{ always() }}
        uses: actions/upload-artifact@v3.1.0
        with:
          name: test-results-xml
          path: results/*.xml

      - name: Download Artifacts
        if: ${{ always() }}
        uses: actions/download-artifact@v3.0.1
        with:
          path: artifacts

      - name: Publish Test Results
        if: ${{ always() }}
        uses: EnricoMi/publish-unit-test-result-action@v2.4.2
        with:
          junit_files: artifacts/**/*.xml

